project:
  type: website
  render:
    - "**/*.qmd"
    - "!shared/templates/**"
    - "!d2l/**"


website:
  title: "CMSC 2208 : Introduction to Machine Learning"
  reader-mode: false
  navbar:
    left:
      - href: index.qmd
        text: Home      

  

  sidebar:
    style: "docked"
    search: true

    # optional
    # logo: shared/assets/course-badge.png
    # logo-alt: "Course badge"
    # logo-href: index.qmd

    tools:
      - icon: chat-dots
        href: https://discord.gg/az8cmeqJdc
        aria-label: Discord
      - icon: book-half
        href: https://sctcc.learn.minnstate.edu/d2l/login
        aria-label: D2L
    
    
    
    
    contents:
      - section: "Course information"
        contents:
          - href: course/syllabus.qmd
            text: Syllabus
          - href: course/schedule.qmd
            text: Schedule
          - href: shared/policies/office-hours.qmd
            text: Office Hours
          - href: shared/policies/homework-coursework.qmd
            text: Assignment Policies
          - href: shared/policies/general-policies.qmd
            text: General Policies
          - href: shared/policies/ai-policy.qmd
            text: AI Policy


      - section: "Weekly Overview"
        contents:
          - href: weekly-overview/week-01/index.qmd
            text: Week 1
          - href: weekly-overview/week-02/index.qmd
            text: Week 2

      - section: "Weekly Assignments"
        contents:
          - href: assignments/week-01/index.qmd
            text: Week 1
          - href: assignments/week-02/index.qmd
            text: Week 2

      - section: "Guides"
        contents:
          - section: "Week 1"
            contents:
              - href: shared/guides/setup/miniconda.qmd
                text: Miniconda Setup
              - href: shared/guides/setup/jupyter-learning-links.qmd
                text: Jupyter Learning Links
          - section: "Week 2"
            contents:
              - href: shared/guides/cmsc-2208/week-02/cmsc-2208-chap-02-learning-resources.qmd
                text: Chapter 3 Reference Videos


format:
  html:
    toc: false
    date-modified: last-modified
    theme:
      light: cosmo
      dark: darkly
    css:
      - shared/assets/course.css
      - styles.css
    include-after-body:
      - text: |
          <script type="text/javascript">
            document.addEventListener("DOMContentLoaded", function() {
              var elements = document.querySelectorAll('[aria-label]');
              for (var i = 0; i < elements.length; i++) {
                var ariaLabel = elements[i].getAttribute('aria-label');
                elements[i].setAttribute('data-bs-title', ariaLabel);
                elements[i].setAttribute('data-bs-toggle', 'tooltip');
                elements[i].setAttribute('data-bs-placement', 'bottom');
              }
              const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]');
              const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl));
            });
          </script>

        




